//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicNotebook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginAttempt
    {
        public int Id { get; set; }
        public int attempts { get; set; }
    
        public virtual Secretary Secretary { get; set; }
    }
}
