//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicNotebook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Appointments = new HashSet<Appointment>();
        }

        [Required(ErrorMessage = "Cédula requerida")]
        public int id { get; set; }

        [Required(ErrorMessage = "Ingrese nombre")]
        public string name { get; set; }

        [Required(ErrorMessage = "Ingrese apellido")]
        public string lastName1 { get; set; }

        public string lastName2 { get; set; }

        [Required(ErrorMessage = "Ingrese correo")]
        public string email { get; set; }

        [Required(ErrorMessage = "Ingrese teléfono")]
        public int phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
