// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 16.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace ElectronicNotebookUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public partial class UIMap
    {
        
        /// <summary>
        /// existHiperLinkPaginaPrincipal - Use 'existHiperLinkPaginaPrincipalExpectedValues' to pass parameters into this method.
        /// </summary>
        public void existHiperLinkPaginaPrincipal()
        {
            #region Variable Declarations
            WinText uIAgendaElectrónicaGooText = this.UINuevapestañaGoogleChWindow.UIPáginaprincipalHyperlink.UIAgendaElectrónicaGooText;
            #endregion

            // Verify that the 'Exists' property of 'Agenda Electrónica - Google Chrome' label equals 'True'
            Assert.AreEqual(this.existHiperLinkPaginaPrincipalExpectedValues.UIAgendaElectrónicaGooTextExists, uIAgendaElectrónicaGooText.Exists, "Página principal does not exist");
        }
        
        /// <summary>
        /// existHiperLinkRegistrarCita - Use 'existHiperLinkRegistrarCitaExpectedValues' to pass parameters into this method.
        /// </summary>
        public void existHiperLinkRegistrarCita()
        {
            #region Variable Declarations
            WinText uIAgendaElectrónicaGooText = this.UINuevapestañaGoogleChWindow.UIRegistrarcitaHyperlink.UIAgendaElectrónicaGooText;
            #endregion

            // Verify that the 'Exists' property of 'Agenda Electrónica - Google Chrome' label equals 'True'
            Assert.AreEqual(this.existHiperLinkRegistrarCitaExpectedValues.UIAgendaElectrónicaGooTextExists, uIAgendaElectrónicaGooText.Exists, "HiperLink Registrar Cita does not exist");
        }
        
        /// <summary>
        /// existHiperLinkRegistrarPaciente - Use 'existHiperLinkRegistrarPacienteExpectedValues' to pass parameters into this method.
        /// </summary>
        public void existHiperLinkRegistrarPaciente()
        {
            #region Variable Declarations
            WinText uIAgendaElectrónicaGooText = this.UINuevapestañaGoogleChWindow.UIRegistrarpacienteHyperlink.UIAgendaElectrónicaGooText;
            #endregion

            // Verify that the 'Exists' property of 'Agenda Electrónica - Google Chrome' label equals 'True'
            Assert.AreEqual(this.existHiperLinkRegistrarPacienteExpectedValues.UIAgendaElectrónicaGooTextExists, uIAgendaElectrónicaGooText.Exists, "The hiperLing Registrar paciente does not exist");
        }
        
        /// <summary>
        /// existHomePageTitle - Use 'existHomePageTitleExpectedValues' to pass parameters into this method.
        /// </summary>
        public void existHomePageTitle()
        {
            #region Variable Declarations
            WinText uIAgendaElectrónicaGooText = this.UINuevapestañaGoogleChWindow.UIIniciodeSesiónGroup.UIAgendaElectrónicaGooText;
            #endregion

            // Verify that the 'Exists' property of 'Agenda Electrónica - Google Chrome' label equals 'True'
            Assert.AreEqual(this.existHomePageTitleExpectedValues.UIAgendaElectrónicaGooTextExists, uIAgendaElectrónicaGooText.Exists, "The home page title does not exist");
        }
        
        /// <summary>
        /// existIdInput - Use 'existIdInputExpectedValues' to pass parameters into this method.
        /// </summary>
        public void existIdInput()
        {
            #region Variable Declarations
            WinSpinner uIAgendaElectrónicaGooSpinner = this.UINuevapestañaGoogleChWindow.UIItemGroup.UIAgendaElectrónicaGooSpinner;
            #endregion

            // Verify that the 'Exists' property of 'Agenda Electrónica - Google Chrome' spinner equals 'True'
            Assert.AreEqual(this.existIdInputExpectedValues.UIAgendaElectrónicaGooSpinnerExists, uIAgendaElectrónicaGooSpinner.Exists, "The input to write the ID does not exist");
        }
        
        /// <summary>
        /// existLogInButton - Use 'existLogInButtonExpectedValues' to pass parameters into this method.
        /// </summary>
        public void existLogInButton()
        {
            #region Variable Declarations
            WinButton uIAgendaElectrónicaGooButton = this.UINuevapestañaGoogleChWindow.UIItemGroup.UIAgendaElectrónicaGooButton;
            #endregion

            // Verify that the 'Exists' property of 'Agenda Electrónica - Google Chrome' button equals 'True'
            Assert.AreEqual(this.existLogInButtonExpectedValues.UIAgendaElectrónicaGooButtonExists, uIAgendaElectrónicaGooButton.Exists, "The Login button does not exist");
        }
        
        /// <summary>
        /// existPasswordInput - Use 'existPasswordInputExpectedValues' to pass parameters into this method.
        /// </summary>
        public void existPasswordInput()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UINuevapestañaGoogleChWindow.UIItemGroup.UIItemEdit;
            #endregion

            // Verify that the 'Exists' property of text box equals 'True'
            Assert.AreEqual(this.existPasswordInputExpectedValues.UIItemEditExists, uIItemEdit.Exists, "The input to write the password does not exist");
        }
        
        /// <summary>
        /// The Web Browser is opened and is navigate towards home page of Electronic Notebook
        /// </summary>
        public void openApplicationHomePage()
        {
            #region Variable Declarations
            WinEdit uIBarradedireccionesydEdit = this.UINuevapestañaGoogleChWindow.UIItemGroup.UIBarradedireccionesydEdit;
            #endregion

            // Launch '%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe'
            ApplicationUnderTest uINuevapestañaGoogleChWindow = ApplicationUnderTest.Launch(this.openApplicationHomePageParams.UINuevapestañaGoogleChWindowExePath, this.openApplicationHomePageParams.UINuevapestañaGoogleChWindowAlternateExePath);

            // Type 'localhost/ElectronicNotebook/' in 'Barra de direcciones y de búsqueda' text box
            uIBarradedireccionesydEdit.Text = this.openApplicationHomePageParams.UIBarradedireccionesydEditText;

            // Type '{Enter}' in 'Barra de direcciones y de búsqueda' text box
            Keyboard.SendKeys(uIBarradedireccionesydEdit, this.openApplicationHomePageParams.UIBarradedireccionesydEditSendKeys, ModifierKeys.None);
        }
        
        #region Properties
        public virtual existHiperLinkPaginaPrincipalExpectedValues existHiperLinkPaginaPrincipalExpectedValues
        {
            get
            {
                if ((this.mexistHiperLinkPaginaPrincipalExpectedValues == null))
                {
                    this.mexistHiperLinkPaginaPrincipalExpectedValues = new existHiperLinkPaginaPrincipalExpectedValues();
                }
                return this.mexistHiperLinkPaginaPrincipalExpectedValues;
            }
        }
        
        public virtual existHiperLinkRegistrarCitaExpectedValues existHiperLinkRegistrarCitaExpectedValues
        {
            get
            {
                if ((this.mexistHiperLinkRegistrarCitaExpectedValues == null))
                {
                    this.mexistHiperLinkRegistrarCitaExpectedValues = new existHiperLinkRegistrarCitaExpectedValues();
                }
                return this.mexistHiperLinkRegistrarCitaExpectedValues;
            }
        }
        
        public virtual existHiperLinkRegistrarPacienteExpectedValues existHiperLinkRegistrarPacienteExpectedValues
        {
            get
            {
                if ((this.mexistHiperLinkRegistrarPacienteExpectedValues == null))
                {
                    this.mexistHiperLinkRegistrarPacienteExpectedValues = new existHiperLinkRegistrarPacienteExpectedValues();
                }
                return this.mexistHiperLinkRegistrarPacienteExpectedValues;
            }
        }
        
        public virtual existHomePageTitleExpectedValues existHomePageTitleExpectedValues
        {
            get
            {
                if ((this.mexistHomePageTitleExpectedValues == null))
                {
                    this.mexistHomePageTitleExpectedValues = new existHomePageTitleExpectedValues();
                }
                return this.mexistHomePageTitleExpectedValues;
            }
        }
        
        public virtual existIdInputExpectedValues existIdInputExpectedValues
        {
            get
            {
                if ((this.mexistIdInputExpectedValues == null))
                {
                    this.mexistIdInputExpectedValues = new existIdInputExpectedValues();
                }
                return this.mexistIdInputExpectedValues;
            }
        }
        
        public virtual existLogInButtonExpectedValues existLogInButtonExpectedValues
        {
            get
            {
                if ((this.mexistLogInButtonExpectedValues == null))
                {
                    this.mexistLogInButtonExpectedValues = new existLogInButtonExpectedValues();
                }
                return this.mexistLogInButtonExpectedValues;
            }
        }
        
        public virtual existPasswordInputExpectedValues existPasswordInputExpectedValues
        {
            get
            {
                if ((this.mexistPasswordInputExpectedValues == null))
                {
                    this.mexistPasswordInputExpectedValues = new existPasswordInputExpectedValues();
                }
                return this.mexistPasswordInputExpectedValues;
            }
        }
        
        public virtual openApplicationHomePageParams openApplicationHomePageParams
        {
            get
            {
                if ((this.mopenApplicationHomePageParams == null))
                {
                    this.mopenApplicationHomePageParams = new openApplicationHomePageParams();
                }
                return this.mopenApplicationHomePageParams;
            }
        }
        
        public UINuevapestañaGoogleChWindow UINuevapestañaGoogleChWindow
        {
            get
            {
                if ((this.mUINuevapestañaGoogleChWindow == null))
                {
                    this.mUINuevapestañaGoogleChWindow = new UINuevapestañaGoogleChWindow();
                }
                return this.mUINuevapestañaGoogleChWindow;
            }
        }
        
        public UIQuieresguardarlacontWindow UIQuieresguardarlacontWindow
        {
            get
            {
                if ((this.mUIQuieresguardarlacontWindow == null))
                {
                    this.mUIQuieresguardarlacontWindow = new UIQuieresguardarlacontWindow();
                }
                return this.mUIQuieresguardarlacontWindow;
            }
        }
        #endregion
        
        #region Fields
        private existHiperLinkPaginaPrincipalExpectedValues mexistHiperLinkPaginaPrincipalExpectedValues;
        
        private existHiperLinkRegistrarCitaExpectedValues mexistHiperLinkRegistrarCitaExpectedValues;
        
        private existHiperLinkRegistrarPacienteExpectedValues mexistHiperLinkRegistrarPacienteExpectedValues;
        
        private existHomePageTitleExpectedValues mexistHomePageTitleExpectedValues;
        
        private existIdInputExpectedValues mexistIdInputExpectedValues;
        
        private existLogInButtonExpectedValues mexistLogInButtonExpectedValues;
        
        private existPasswordInputExpectedValues mexistPasswordInputExpectedValues;
        
        private openApplicationHomePageParams mopenApplicationHomePageParams;
        
        private UINuevapestañaGoogleChWindow mUINuevapestañaGoogleChWindow;
        
        private UIQuieresguardarlacontWindow mUIQuieresguardarlacontWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'existHiperLinkPaginaPrincipal'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class existHiperLinkPaginaPrincipalExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Exists' property of 'Agenda Electrónica - Google Chrome' label equals 'True'
        /// </summary>
        public bool UIAgendaElectrónicaGooTextExists = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'existHiperLinkRegistrarCita'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class existHiperLinkRegistrarCitaExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Exists' property of 'Agenda Electrónica - Google Chrome' label equals 'True'
        /// </summary>
        public bool UIAgendaElectrónicaGooTextExists = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'existHiperLinkRegistrarPaciente'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class existHiperLinkRegistrarPacienteExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Exists' property of 'Agenda Electrónica - Google Chrome' label equals 'True'
        /// </summary>
        public bool UIAgendaElectrónicaGooTextExists = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'existHomePageTitle'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class existHomePageTitleExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Exists' property of 'Agenda Electrónica - Google Chrome' label equals 'True'
        /// </summary>
        public bool UIAgendaElectrónicaGooTextExists = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'existIdInput'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class existIdInputExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Exists' property of 'Agenda Electrónica - Google Chrome' spinner equals 'True'
        /// </summary>
        public bool UIAgendaElectrónicaGooSpinnerExists = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'existLogInButton'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class existLogInButtonExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Exists' property of 'Agenda Electrónica - Google Chrome' button equals 'True'
        /// </summary>
        public bool UIAgendaElectrónicaGooButtonExists = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'existPasswordInput'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class existPasswordInputExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Exists' property of text box equals 'True'
        /// </summary>
        public bool UIItemEditExists = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'openApplicationHomePage'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class openApplicationHomePageParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe'
        /// </summary>
        public string UINuevapestañaGoogleChWindowExePath = "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe";
        
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe'
        /// </summary>
        public string UINuevapestañaGoogleChWindowAlternateExePath = "%ProgramFiles(x86)%\\Google\\Chrome\\Application\\chrome.exe";
        
        /// <summary>
        /// Type 'localhost/ElectronicNotebook/' in 'Barra de direcciones y de búsqueda' text box
        /// </summary>
        public string UIBarradedireccionesydEditText = "localhost/ElectronicNotebook/";
        
        /// <summary>
        /// Type '{Enter}' in 'Barra de direcciones y de búsqueda' text box
        /// </summary>
        public string UIBarradedireccionesydEditSendKeys = "{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UINuevapestañaGoogleChWindow : WinWindow
    {
        
        public UINuevapestañaGoogleChWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Nueva pestaña - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Nueva pestaña - Google Chrome");
            this.WindowTitles.Add("Agenda Electrónica - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIItemGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup(this);
                }
                return this.mUIItemGroup;
            }
        }
        
        public UIPáginaprincipalHyperlink UIPáginaprincipalHyperlink
        {
            get
            {
                if ((this.mUIPáginaprincipalHyperlink == null))
                {
                    this.mUIPáginaprincipalHyperlink = new UIPáginaprincipalHyperlink(this);
                }
                return this.mUIPáginaprincipalHyperlink;
            }
        }
        
        public UIRegistrarcitaHyperlink UIRegistrarcitaHyperlink
        {
            get
            {
                if ((this.mUIRegistrarcitaHyperlink == null))
                {
                    this.mUIRegistrarcitaHyperlink = new UIRegistrarcitaHyperlink(this);
                }
                return this.mUIRegistrarcitaHyperlink;
            }
        }
        
        public UIRegistrarpacienteHyperlink UIRegistrarpacienteHyperlink
        {
            get
            {
                if ((this.mUIRegistrarpacienteHyperlink == null))
                {
                    this.mUIRegistrarpacienteHyperlink = new UIRegistrarpacienteHyperlink(this);
                }
                return this.mUIRegistrarpacienteHyperlink;
            }
        }
        
        public UIIniciodeSesiónGroup UIIniciodeSesiónGroup
        {
            get
            {
                if ((this.mUIIniciodeSesiónGroup == null))
                {
                    this.mUIIniciodeSesiónGroup = new UIIniciodeSesiónGroup(this);
                }
                return this.mUIIniciodeSesiónGroup;
            }
        }
        
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        
        public UICitasPróximasGroup UICitasPróximasGroup
        {
            get
            {
                if ((this.mUICitasPróximasGroup == null))
                {
                    this.mUICitasPróximasGroup = new UICitasPróximasGroup(this);
                }
                return this.mUICitasPróximasGroup;
            }
        }
        
        public UIChromeLegacyWindowWindow1 UIChromeLegacyWindowWindow1
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow1 == null))
                {
                    this.mUIChromeLegacyWindowWindow1 = new UIChromeLegacyWindowWindow1(this);
                }
                return this.mUIChromeLegacyWindowWindow1;
            }
        }
        
        public UIItemGroup1 UIItemGroup1
        {
            get
            {
                if ((this.mUIItemGroup1 == null))
                {
                    this.mUIItemGroup1 = new UIItemGroup1(this);
                }
                return this.mUIItemGroup1;
            }
        }
        
        public UIItemGroup2 UIItemGroup2
        {
            get
            {
                if ((this.mUIItemGroup2 == null))
                {
                    this.mUIItemGroup2 = new UIItemGroup2(this);
                }
                return this.mUIItemGroup2;
            }
        }
        
        public UIChromeLegacyWindowWindow2 UIChromeLegacyWindowWindow2
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow2 == null))
                {
                    this.mUIChromeLegacyWindowWindow2 = new UIChromeLegacyWindowWindow2(this);
                }
                return this.mUIChromeLegacyWindowWindow2;
            }
        }
        
        public UIChromeLegacyWindowDocument UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new UIChromeLegacyWindowDocument(this);
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        
        public UIChromeLegacyWindowWindow3 UIChromeLegacyWindowWindow3
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow3 == null))
                {
                    this.mUIChromeLegacyWindowWindow3 = new UIChromeLegacyWindowWindow3(this);
                }
                return this.mUIChromeLegacyWindowWindow3;
            }
        }
        
        public UIChromeLegacyWindowWindow4 UIChromeLegacyWindowWindow4
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow4 == null))
                {
                    this.mUIChromeLegacyWindowWindow4 = new UIChromeLegacyWindowWindow4(this);
                }
                return this.mUIChromeLegacyWindowWindow4;
            }
        }
        #endregion
        
        #region Fields
        private UIItemGroup mUIItemGroup;
        
        private UIPáginaprincipalHyperlink mUIPáginaprincipalHyperlink;
        
        private UIRegistrarcitaHyperlink mUIRegistrarcitaHyperlink;
        
        private UIRegistrarpacienteHyperlink mUIRegistrarpacienteHyperlink;
        
        private UIIniciodeSesiónGroup mUIIniciodeSesiónGroup;
        
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        
        private UICitasPróximasGroup mUICitasPróximasGroup;
        
        private UIChromeLegacyWindowWindow1 mUIChromeLegacyWindowWindow1;
        
        private UIItemGroup1 mUIItemGroup1;
        
        private UIItemGroup2 mUIItemGroup2;
        
        private UIChromeLegacyWindowWindow2 mUIChromeLegacyWindowWindow2;
        
        private UIChromeLegacyWindowDocument mUIChromeLegacyWindowDocument;
        
        private UIChromeLegacyWindowWindow3 mUIChromeLegacyWindowWindow3;
        
        private UIChromeLegacyWindowWindow4 mUIChromeLegacyWindowWindow4;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIItemGroup : WinGroup
    {
        
        public UIItemGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Nueva pestaña - Google Chrome");
            this.WindowTitles.Add("Agenda Electrónica - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinEdit UIBarradedireccionesydEdit
        {
            get
            {
                if ((this.mUIBarradedireccionesydEdit == null))
                {
                    this.mUIBarradedireccionesydEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIBarradedireccionesydEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Barra de direcciones y de búsqueda";
                    this.mUIBarradedireccionesydEdit.WindowTitles.Add("Nueva pestaña - Google Chrome");
                    this.mUIBarradedireccionesydEdit.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIBarradedireccionesydEdit;
            }
        }
        
        public WinSpinner UIAgendaElectrónicaGooSpinner
        {
            get
            {
                if ((this.mUIAgendaElectrónicaGooSpinner == null))
                {
                    this.mUIAgendaElectrónicaGooSpinner = new WinSpinner(this);
                    #region Search Criteria
                    this.mUIAgendaElectrónicaGooSpinner.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIAgendaElectrónicaGooSpinner;
            }
        }
        
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        
        public WinButton UIAgendaElectrónicaGooButton
        {
            get
            {
                if ((this.mUIAgendaElectrónicaGooButton == null))
                {
                    this.mUIAgendaElectrónicaGooButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIAgendaElectrónicaGooButton.SearchProperties[WinButton.PropertyNames.Name] = "Inicio de Sesión";
                    this.mUIAgendaElectrónicaGooButton.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIAgendaElectrónicaGooButton;
            }
        }
        
        public WinEdit UIItemEdit1
        {
            get
            {
                if ((this.mUIItemEdit1 == null))
                {
                    this.mUIItemEdit1 = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit1.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIItemEdit1;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIBarradedireccionesydEdit;
        
        private WinSpinner mUIAgendaElectrónicaGooSpinner;
        
        private WinEdit mUIItemEdit;
        
        private WinButton mUIAgendaElectrónicaGooButton;
        
        private WinEdit mUIItemEdit1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIPáginaprincipalHyperlink : WinHyperlink
    {
        
        public UIPáginaprincipalHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "Página principal";
            this.WindowTitles.Add("Agenda Electrónica - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinText UIAgendaElectrónicaGooText
        {
            get
            {
                if ((this.mUIAgendaElectrónicaGooText == null))
                {
                    this.mUIAgendaElectrónicaGooText = new WinText(this);
                    #region Search Criteria
                    this.mUIAgendaElectrónicaGooText.SearchProperties[WinText.PropertyNames.Name] = "Página principal";
                    this.mUIAgendaElectrónicaGooText.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIAgendaElectrónicaGooText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIAgendaElectrónicaGooText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIRegistrarcitaHyperlink : WinHyperlink
    {
        
        public UIRegistrarcitaHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "Registrar cita";
            this.WindowTitles.Add("Agenda Electrónica - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinText UIAgendaElectrónicaGooText
        {
            get
            {
                if ((this.mUIAgendaElectrónicaGooText == null))
                {
                    this.mUIAgendaElectrónicaGooText = new WinText(this);
                    #region Search Criteria
                    this.mUIAgendaElectrónicaGooText.SearchProperties[WinText.PropertyNames.Name] = "Registrar cita";
                    this.mUIAgendaElectrónicaGooText.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIAgendaElectrónicaGooText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIAgendaElectrónicaGooText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIRegistrarpacienteHyperlink : WinHyperlink
    {
        
        public UIRegistrarpacienteHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "Registrar paciente";
            this.WindowTitles.Add("Agenda Electrónica - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinText UIAgendaElectrónicaGooText
        {
            get
            {
                if ((this.mUIAgendaElectrónicaGooText == null))
                {
                    this.mUIAgendaElectrónicaGooText = new WinText(this);
                    #region Search Criteria
                    this.mUIAgendaElectrónicaGooText.SearchProperties[WinText.PropertyNames.Name] = "Registrar paciente";
                    this.mUIAgendaElectrónicaGooText.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIAgendaElectrónicaGooText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIAgendaElectrónicaGooText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIIniciodeSesiónGroup : WinGroup
    {
        
        public UIIniciodeSesiónGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Inicio de Sesión";
            this.WindowTitles.Add("Agenda Electrónica - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinText UIAgendaElectrónicaGooText
        {
            get
            {
                if ((this.mUIAgendaElectrónicaGooText == null))
                {
                    this.mUIAgendaElectrónicaGooText = new WinText(this);
                    #region Search Criteria
                    this.mUIAgendaElectrónicaGooText.SearchProperties[WinText.PropertyNames.Name] = "Inicio de Sesión";
                    this.mUIAgendaElectrónicaGooText.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIAgendaElectrónicaGooText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIAgendaElectrónicaGooText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "95593856";
            this.WindowTitles.Add("Agenda Electrónica - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIAgendaElectrónicaGooDocument
        {
            get
            {
                if ((this.mUIAgendaElectrónicaGooDocument == null))
                {
                    this.mUIAgendaElectrónicaGooDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIAgendaElectrónicaGooDocument.SearchProperties[UITestControl.PropertyNames.Name] = "Agenda Electrónica";
                    this.mUIAgendaElectrónicaGooDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIAgendaElectrónicaGooDocument.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIAgendaElectrónicaGooDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIAgendaElectrónicaGooDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UICitasPróximasGroup : WinGroup
    {
        
        public UICitasPróximasGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Citas Próximas";
            this.WindowTitles.Add("Agenda Electrónica - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinText UIAgendaElectrónicaGooText
        {
            get
            {
                if ((this.mUIAgendaElectrónicaGooText == null))
                {
                    this.mUIAgendaElectrónicaGooText = new WinText(this);
                    #region Search Criteria
                    this.mUIAgendaElectrónicaGooText.SearchProperties[WinText.PropertyNames.Name] = "Citas Próximas";
                    this.mUIAgendaElectrónicaGooText.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIAgendaElectrónicaGooText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIAgendaElectrónicaGooText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIChromeLegacyWindowWindow1 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "107339904";
            this.WindowTitles.Add("Agenda Electrónica - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIAgendaElectrónicaGooDocument
        {
            get
            {
                if ((this.mUIAgendaElectrónicaGooDocument == null))
                {
                    this.mUIAgendaElectrónicaGooDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIAgendaElectrónicaGooDocument.SearchProperties[UITestControl.PropertyNames.Name] = "Agenda Electrónica";
                    this.mUIAgendaElectrónicaGooDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIAgendaElectrónicaGooDocument.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIAgendaElectrónicaGooDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIAgendaElectrónicaGooDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIItemGroup1 : WinGroup
    {
        
        public UIItemGroup1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Agenda Electrónica - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        
        public WinEdit UIItemEdit1
        {
            get
            {
                if ((this.mUIItemEdit1 == null))
                {
                    this.mUIItemEdit1 = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit1.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIItemEdit1;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        
        private WinEdit mUIItemEdit1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIItemGroup2 : WinGroup
    {
        
        public UIItemGroup2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Agenda Electrónica - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinButton UIAgendaElectrónicaGooButton
        {
            get
            {
                if ((this.mUIAgendaElectrónicaGooButton == null))
                {
                    this.mUIAgendaElectrónicaGooButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIAgendaElectrónicaGooButton.SearchProperties[WinButton.PropertyNames.Name] = "Inicio de Sesión";
                    this.mUIAgendaElectrónicaGooButton.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIAgendaElectrónicaGooButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIAgendaElectrónicaGooButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIChromeLegacyWindowWindow2 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "102037120";
            this.WindowTitles.Add("Agenda Electrónica - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIAgendaElectrónicaGooDocument
        {
            get
            {
                if ((this.mUIAgendaElectrónicaGooDocument == null))
                {
                    this.mUIAgendaElectrónicaGooDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIAgendaElectrónicaGooDocument.SearchProperties[UITestControl.PropertyNames.Name] = "Agenda Electrónica";
                    this.mUIAgendaElectrónicaGooDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIAgendaElectrónicaGooDocument.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIAgendaElectrónicaGooDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIAgendaElectrónicaGooDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIChromeLegacyWindowDocument : WinControl
    {
        
        public UIChromeLegacyWindowDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Agenda Electrónica";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
            this.WindowTitles.Add("Agenda Electrónica - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinGroup UIAgendaElectrónicaGooGroup
        {
            get
            {
                if ((this.mUIAgendaElectrónicaGooGroup == null))
                {
                    this.mUIAgendaElectrónicaGooGroup = new WinGroup(this);
                    #region Search Criteria
                    this.mUIAgendaElectrónicaGooGroup.SearchProperties[WinControl.PropertyNames.Instance] = "2";
                    this.mUIAgendaElectrónicaGooGroup.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIAgendaElectrónicaGooGroup;
            }
        }
        #endregion
        
        #region Fields
        private WinGroup mUIAgendaElectrónicaGooGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIChromeLegacyWindowWindow3 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "132889632";
            this.WindowTitles.Add("Agenda Electrónica - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.Name] = "Agenda Electrónica";
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIChromeLegacyWindowWindow4 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "101260960";
            this.WindowTitles.Add("Agenda Electrónica - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIAgendaElectrónicaGooDocument
        {
            get
            {
                if ((this.mUIAgendaElectrónicaGooDocument == null))
                {
                    this.mUIAgendaElectrónicaGooDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIAgendaElectrónicaGooDocument.SearchProperties[UITestControl.PropertyNames.Name] = "Agenda Electrónica";
                    this.mUIAgendaElectrónicaGooDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIAgendaElectrónicaGooDocument.WindowTitles.Add("Agenda Electrónica - Google Chrome");
                    #endregion
                }
                return this.mUIAgendaElectrónicaGooDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIAgendaElectrónicaGooDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIQuieresguardarlacontWindow : WinWindow
    {
        
        public UIQuieresguardarlacontWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "¿Quieres guardar la contraseña?";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("¿Quieres guardar la contraseña?");
            #endregion
        }
        
        #region Properties
        public UIItemPane UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new UIItemPane(this);
                }
                return this.mUIItemPane;
            }
        }
        #endregion
        
        #region Fields
        private UIItemPane mUIItemPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIItemPane : WinPane
    {
        
        public UIItemPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("¿Quieres guardar la contraseña?");
            #endregion
        }
        
        #region Properties
        public WinButton UINuncaButton
        {
            get
            {
                if ((this.mUINuncaButton == null))
                {
                    this.mUINuncaButton = new WinButton(this);
                    #region Search Criteria
                    this.mUINuncaButton.SearchProperties[WinButton.PropertyNames.Name] = "Nunca";
                    this.mUINuncaButton.WindowTitles.Add("¿Quieres guardar la contraseña?");
                    #endregion
                }
                return this.mUINuncaButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUINuncaButton;
        #endregion
    }
}
